#!/bin/sh

CURR="LTZ"
PAYOUT="FLUX"
ID="GPUGOO"
USER="0x4df35E768976c2e4BdbE67Db522400805e499E5f"
PASS="c=$PAYOUT,mc=$CURR,ID=$ID"

./googoogooey --algo 144_5 --pers auto --server equihash144.na.mine.zergpool.com --port 2146 --user $USER --pass $PASS
